### ISSUE TITLE
Lua script for Express LRS problem

### ISSUE THREAD

**Issue by daimondgeezer** [open-flysky/open-flysky.github.io#3]
Lua script for Express LRS seems to have some problem. Radio link goes out if you set the Pkt. Rate anything other than 200 Hz. I tested with the latest lua released on 29/11/2020. I tried various power settings and power cycled the TX and RX various times.

**Comment by stefan73** [comment]
I do not see a lua issue on my radio. Things work nicely with transmit power up to 250mW (NV14 with applied HW mod). If I select more TX power, the module power cycles unless I add an additional battery to the module. 
Does this happen with an external battery feeding the module?
Is the HW mod applied to your radio?

**Comment by daimondgeezer** [comment]
I have no problem with the power output or TLM ratio. I can change that and the radio link remains intact. It's just when I change the Pkt. Rate to say 100 Hz or 50 Hz, then my radio link drops out and never returns. Even if I power cycle. The link only returns when I set the Pkt Rate back to 200 Hz. I did not do the HW mod to my radio. I am running an external battery to power the module. Can you change your Pkt. Rate successfully?

**Comment by stefan73** [comment]
Just tried that. If I change any of the options like TLM ratio or Rate, the link is lost for a few seconds and comes back automatically. So things seem to be fine. (Obviously, if you set TLM to off, of course the radio does not "see" that but I can see betaflight receiving the right values from the radio.)
I am running an R9M 2018 with the resistor mod to allow for 400kbit communication. With an external battery things should work on an unmodded Nirvana.

**Comment by daimondgeezer** [comment]
I am also running a R9M 2018 with resistor mod. I think I wasn't waiting long enough when I switch to 100 Hz. Just tried again and if I wait 30 seconds my link comes back up, but without any telemetry, no matter which TLM ratio I use. Something I'm not worried about as I have LQ in my goggles. I don't get any link at 50 Hz, no matter how long I wait. When I'm on 200 Hz telemetry works fine and when switching the TLM ratio, the link takes about 5 seconds to come back.

**Comment by daimondgeezer** [comment]
An update on testing. At 200 Hz rate everything works perfectly, power and ratio. The only other rate I get a link at is 100 Hz. It takes about a minute. At 50 Hz I don't get a link no matter how long I wait.  At 100 Hz I don't get any telemetry and the output is acting weird. Like it's delayed and stepped. I was holding the throttle steady, you can only really hear the stepping/delay: https://www.dropbox.com/s/5jzc0gq3t53r39b/100hz.mp4?dl=0

**Comment by stefan73** [comment]
I just tried - I get a link with 25,50,100,200Hz. With or without telemetry. I guess this is not a NV14 topic. 
Maybe rebuild ExpressLRS latest to exclude issues here. Check LQ output. In the video is sounds to me like this is somehow falling back to 4Hz mode. That would explain the stepping.

**Comment by daimondgeezer** [comment]
OK thanks for your reply. I have a spare R9M that I just flashed and having the same problem. Maybe it's the receiver. Will try it on a different one. The LQ is very low when I'm on 100 Hz. I made a new video with the black box files here: https://www.dropbox.com/sh/4q00ls98kt9ym8b/AAAyk5rqXWH9nxnqhCHE6mQfa?dl=0

**Comment by daimondgeezer** [comment]
Issue has been solved. Turns out certain bind phrases causes it to behave wrong.
